version: "3"
services:
  friends-management:
    container_name: friends-management
    image: friends-management
    build: .
    command: "npm run debug"
    volumes:
      - ".:/friends-api"
      - "/friends-api/node_modules"
    ports:
      - "8999:3000"
      - "9228:9228"
    env_file:
      - .env
    links:
      - friends-management-mongo
    depends_on:
      - friends-management-mongo
  friends-management-mongo:
    image: "mongo:3.6.6"
    container_name: friends-management-mongo
    ports:
      - "8998:27017"
    volumes:
      - "./.data/mongo:/data/db"
      - "./.data/mongoconfigdb:/data/configdb"
  friends-doc:
    image: "swaggerapi/swagger-ui:v3.3.1"
    container_name: friends-doc
    ports:
      - "5400:8080"
    volumes:
      - "./swagger/:/usr/share/nginx/html/"
      - "./doc/api/:/usr/share/nginx/html/api"
      - "./swagger/nginx.conf:/etc/nginx/nginx.conf"
